### ISSUE TITLE
Support Python & Scala simultaneously？

### ISSUE THREAD

**Issue by databig** [hohonuuli/sparknotebook#2]
Hi, It is possible to support Python & Scala simultaneously in Spark Notebook.
That means I can choose this line's language, then program, like Leetcode did.
Because different guys may prefer various languages.
Tks.

**Comment by databig** [comment]
@hohonuuli  Could you please follow?

**Comment by hohonuuli** [comment]
@databig I suspect not as they have different underlying runtimes. But honestly, I don't know enough about Spark internals to know how data is being shuttled between Python and the JVM. It might be possible ... but your best bet would be to hit up the Spark developers list and ask about Spark and Python being able to share the same SparkContext.
